# Generated by Django 5.2.3 on 2025-06-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_id', models.CharField()),
                ('installed_version', models.CharField()),
                ('modloader', models.CharField()),
                ('mc_version', models.CharField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
