# Generated by Django 5.2.3 on 2025-06-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modlist',
            name='name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
