# Generated by Django 5.2.3 on 2025-06-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modlist', '0002_modlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modlist',
            name='installed_version',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='modlist',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='modlist',
            name='mc_version',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='modlist',
            name='mod_id',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='modlist',
            name='modloader',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='modlist',
            name='name',
            field=models.CharField(null=True),
        ),
    ]
