# Generated by Django 5.2.3 on 2025-06-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modlist', '0003_alter_modlist_installed_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedMods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=8, null=True)),
                ('mod_name', models.CharField(null=True)),
                ('installed_version', models.CharField(null=True)),
                ('installed_version_type', models.CharField(choices=[('release', 'Release'), ('beta', 'Beta'), ('alpha', 'Alpha')], null=True)),
                ('installed_mc_version', models.CharField(choices=[('1.21.5', '1.21.5'), ('1.21.6', '1.21.6'), ('1.21.7', '1.21.7')], null=True)),
                ('latest_version', models.CharField(null=True)),
                ('latest_version_type', models.CharField(choices=[('release', 'Release'), ('beta', 'Beta'), ('alpha', 'Alpha')], null=True)),
                ('latest_mc_version', models.CharField(choices=[('1.21.5', '1.21.5'), ('1.21.6', '1.21.6'), ('1.21.7', '1.21.7')], null=True)),
                ('last_updated', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Modlist',
        ),
    ]
