# Generated by Django 5.2.3 on 2025-06-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modlist', '0004_trackedmods_delete_modlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackedmods',
            name='id',
        ),
        migrations.AlterField(
            model_name='trackedmods',
            name='project_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
